const { pool } = require('../config/database');
const createCsvWriter = require('csv-writer').createObjectCsvWriter;
const path = require('path');
const fs = require('fs');

/**
 * Report Controller
 * Handles data export and reporting
 */
class ReportController {

  /**
   * Export event registrations as CSV
   * GET /api/reports/events/:eventId/export
   */
  static async exportEventRegistrations(req, res, next) {
    try {
      const { eventId } = req.params;

      // Get event details
      const [events] = await pool.query(
        'SELECT * FROM events WHERE id = ? AND created_by = ?',
        [eventId, req.user.id]
      );

      if (events.length === 0) {
        return res.status(404).json({
          success: false,
          message: 'Event not found or access denied'
        });
      }

      const event = events[0];

      // Get all registrations for this event
      const [registrations] = await pool.query(`
        SELECT 
          r.id as registration_id,
          u.name as attendee_name,
          u.email as attendee_email,
          u.phone as attendee_phone,
          r.status,
          r.registration_date,
          r.cancellation_date,
          r.qr_token,
          CASE 
            WHEN r.status = 'registered' THEN 'Active'
            WHEN r.status = 'attended' THEN 'Attended'
            WHEN r.status = 'cancelled' THEN 'Cancelled'
          END as status_label
        FROM registrations r
        JOIN users u ON r.user_id = u.id
        WHERE r.event_id = ?
        ORDER BY r.registration_date DESC
      `, [eventId]);

      // Generate CSV file
      const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
      const fileName = `event-${eventId}-registrations-${timestamp}.csv`;
      const filePath = path.join(__dirname, '..', 'exports', fileName);

      // Ensure exports directory exists
      const exportsDir = path.join(__dirname, '..', 'exports');
      if (!fs.existsSync(exportsDir)) {
        fs.mkdirSync(exportsDir, { recursive: true });
      }

      const csvWriter = createCsvWriter({
        path: filePath,
        header: [
          { id: 'registration_id', title: 'Registration ID' },
          { id: 'attendee_name', title: 'Attendee Name' },
          { id: 'attendee_email', title: 'Email' },
          { id: 'attendee_phone', title: 'Phone' },
          { id: 'status_label', title: 'Status' },
          { id: 'registration_date', title: 'Registration Date' },
          { id: 'cancellation_date', title: 'Cancellation Date' },
          { id: 'qr_token', title: 'QR Token' }
        ]
      });

      await csvWriter.writeRecords(registrations);

      // Also prepare summary
      const totalRegistrations = registrations.length;
      const activeRegistrations = registrations.filter(r => r.status === 'registered').length;
      const cancelledRegistrations = registrations.filter(r => r.status === 'cancelled').length;
      const attendedRegistrations = registrations.filter(r => r.status === 'attended').length;

      // Add summary rows
      const summaryContent = `
Event: "${event.title}"
Date: ${event.date}
Location: ${event.location}
Capacity: ${event.capacity}
Available Slots: ${event.available_slots}

Summary:
- Total Registrations: ${totalRegistrations}
- Active: ${activeRegistrations}
- Attended: ${attendedRegistrations}
- Cancelled: ${cancelledRegistrations}
- Attendance Rate: ${event.capacity > 0 ? Math.round((activeRegistrations / event.capacity) * 100) : 0}%

Exported on: ${new Date().toLocaleString()}
Generated by: ${req.user.name} (${req.user.email})
`.trim();

      // Append summary to file
      fs.appendFileSync(filePath, '\n\n' + summaryContent.replace(/\n/g, '\r\n'));

      // Send file for download
      res.download(filePath, fileName, (err) => {
        if (err) {
          console.error('Download error:', err);
          return res.status(500).json({
            success: false,
            message: 'Failed to download file'
          });
        }
        
        // Clean up file after download
        setTimeout(() => {
          if (fs.existsSync(filePath)) {
            fs.unlinkSync(filePath);
          }
        }, 5000);
      });

    } catch (error) {
      next(error);
    }
  }

  /**
   * Get admin dashboard summary
   * GET /api/reports/dashboard
   */
  static async getDashboardSummary(req, res, next) {
    try {
      // Total events
      const [eventCount] = await pool.query('SELECT COUNT(*) as total FROM events WHERE created_by = ?', [req.user.id]);
      
      // Events by status
      const [eventsByStatus] = await pool.query(`
        SELECT status, COUNT(*) as count 
        FROM events 
        WHERE created_by = ? 
        GROUP BY status
      `, [req.user.id]);

      // Total vendors
      const [vendorCount] = await pool.query('SELECT COUNT(*) as total FROM vendors');
      
      // Pending vendors
      const [pendingVendors] = await pool.query("SELECT COUNT(*) as total FROM vendors WHERE is_approved = FALSE");
      
      // Total registrations
      const [registrationCount] = await pool.query(`
        SELECT COUNT(*) as total FROM registrations r
        JOIN events e ON r.event_id = e.id
        WHERE e.created_by = ?
      `, [req.user.id]);

      // Upcoming events
      const [upcomingEvents] = await pool.query(`
        SELECT * FROM events 
        WHERE created_by = ? AND status = 'published' AND date >= CURDATE()
        ORDER BY date ASC
        LIMIT 5
      `, [req.user.id]);

      // Registrations per event (for charts)
      const [registrationsPerEvent] = await pool.query(`
        SELECT e.title, e.date, COUNT(r.id) as total_registrations,
               SUM(CASE WHEN r.status = 'registered' THEN 1 ELSE 0 END) as active,
               SUM(CASE WHEN r.status = 'cancelled' THEN 1 ELSE 0 END) as cancelled
        FROM events e
        LEFT JOIN registrations r ON e.id = r.event_id
        WHERE e.created_by = ?
        GROUP BY e.id
        ORDER BY e.date DESC
        LIMIT 10
      `, [req.user.id]);

      // Vendor bookings
      const [vendorBookings] = await pool.query(`
        SELECT v.company_name, v.service_type, COUNT(s.id) as total_services,
               (SELECT COUNT(*) FROM services WHERE vendor_id = v.id AND is_available = TRUE) as active_services
        FROM vendors v
        LEFT JOIN services s ON v.id = s.vendor_id
        WHERE v.is_approved = TRUE
        GROUP BY v.id
        ORDER BY total_services DESC
      `);

      res.json({
        success: true,
        data: {
          total_events: eventCount[0].total,
          events_by_status: eventsByStatus,
          total_vendors: vendorCount[0].total,
          pending_vendors: pendingVendors[0].total,
          total_registrations: registrationCount[0].total,
          upcoming_events: upcomingEvents,
          registrations_per_event: registrationsPerEvent,
          vendor_bookings: vendorBookings
        }
      });

    } catch (error) {
      next(error);
    }
  }
}

module.exports = ReportController;